# Generated by Django 2.2.15 on 2020-08-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_blur',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
