# Generated by Django 2.2.15 on 2020-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_image_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
