# Generated by Django 2.2.15 on 2020-08-31 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200828_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='magazines/pdf_files')),
                ('thumbnail', models.ImageField(upload_to='magazines/thumbnail')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'magazine',
                'verbose_name_plural': 'magazines',
            },
        ),
    ]
