# Generated by Django 2.2.15 on 2020-08-31 11:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about_content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_fax',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
