# Generated by Django 2.2.15 on 2020-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200831_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contact_fax',
            field=models.TextField(),
        ),
    ]
