# Generated by Django 2.2.15 on 2020-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200831_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
