# Generated by Django 2.2.15 on 2020-09-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_details',
        ),
    ]
