# Generated by Django 2.2.15 on 2020-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_news_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_crop',
            field=models.ImageField(blank=True, null=True, upload_to='images_crop'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
