# Generated by Django 2.2.15 on 2020-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200901_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about_video',
            field=models.FileField(upload_to='about_video'),
        ),
    ]
