# Generated by Django 2.2.15 on 2020-09-03 14:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
