# Generated by Django 2.2.15 on 2020-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_factory_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='factory/video'),
        ),
    ]
