# Generated by Django 2.2.15 on 2020-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200904_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
