# Generated by Django 2.2.15 on 2020-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200904_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
