# Generated by Django 2.2.15 on 2020-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tender_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='news/thumbnail'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_blur',
            field=models.ImageField(default='', upload_to='images_blur'),
        ),
    ]
