# Generated by Django 2.2.15 on 2020-09-05 12:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200905_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='document_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
