# Generated by Django 2.2.15 on 2020-09-17 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_assocationcontacts_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('who_is', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('organization', models.CharField(max_length=200)),
                ('shipping_method', models.CharField(max_length=100)),
                ('egrpo', models.FileField(upload_to='order_files/egrpo')),
                ('letter', models.FileField(upload_to='order_files/letter')),
                ('contract', models.FileField(upload_to='order_files/contract')),
                ('certificate', models.FileField(upload_to='order_files/certificate')),
                ('state_license', models.FileField(upload_to='order_files/state_license')),
                ('wes_certificate', models.FileField(upload_to='order_files/wes_certificate')),
                ('banking_details', models.FileField(upload_to='order_files/banking_details')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
