# Generated by Django 2.2.15 on 2020-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='content',
            field=models.TextField(),
        ),
    ]
